import LRU from "./lru.js";

const cache = new LRU(3)

cache.push(1, 'one')
console.log(`${cache}`)
console.log('-------------')
cache.push(2, 'two')
console.log(`${cache}`)
console.log('-------------')
cache.push(3, 'three')
console.log(`${cache}`)
console.log('-------------')
cache.get(1)
console.log(`${cache}`)
console.log('-------------')
cache.push(4, 'four')
console.log(`${cache}`)
console.log('-------------')
cache.get(2)
console.log(`${cache}`)
console.log('-------------')
cache.get(3)
console.log(`${cache}`)
console.log('-------------')
cache.push(5, 'five')
console.log(`${cache}`)
console.log('-------------')